### PR TITLE
Implement name_history.

### PR DESCRIPTION
**Pull request by domob1812**
This patch implements name_history in addition to name_show in libcoin.  I'm not sure if we should merge the patch here - instead, I'll also submit the patches to Michael Gronager, and he probably will merge them in libcoin/libcoin.  I think we should keep this repository to track libcoin/libcoin unless there are some changes that aren't going to be committed to libcoin/libcoin ever for some reason.  It seems that I can't submit a pull request against libcoin/libcoin directly - there must be something wrong with how the repositories are forked off each other.

I submit the pull request here nevertheless for reference.

### CODE REVIEW

**Comment by indolering** [comment]
Close this?

**Comment by domob1812** [comment]
Not sure - my plan is to get it merged upstream by Michael, but that hasn't happened since.  I submitted it here for "visibility", in case someone can make use of the code until it is merged upstream.  I don't care if we want to keep it open for this reason or not - feel free to close if you think that's more appropriate.

**Comment by JeremyRand** [comment]
I would suggest leaving it open until it's merged upstream.

**Comment by indolering** [comment]
Agreed, I understand that it's often better to wait for Mike to incorporate our changes upstream but it has been so unstable and taken so long to get these changes included that we should plan on maintaining a fork.

**Pull request closed without merging**
